###
POST http://localhost:3005/categories
Content-Type: application/json

{
    "name": "Débito",
    "published": 1,
    "vl_prev": 0.0,
    "day_prev": 0,
    "ordem": 0,
    "type": "DEB"
}

###
GET http://localhost:3005/categories

###
GET http://localhost:3005/categories/related/credit/2025

###
GET http://localhost:3005/categories/related/debit/2025

###
GET http://localhost:3005/categories/temp/2025

###
GET http://localhost:3005/categories/related


###
GET http://localhost:3005/categories/1

###
DELETE http://localhost:3005/categories/1

###
//PUT objeto inteiro
//PATCH alguns atributos
PATCH http://localhost:3005/categories/1
Content-Type: application/json

{   
    "type": "CRED"
}
